### ISSUE TITLE
give core maintainers npm publish rights

### ISSUE THREAD

**Issue by bcoe** [conventional-changelog/conventional-changelog#166]
so that we can start pushing out some initial releases on top of this mono-repo, @stevemao will need to give a few of the core maintainers publish rights to all of the appropriate npm modules in the `packages/` folder.

A release is then kicked off by running:

`lerna publish`

Which will prompt the person running the release for the appropriate version bumps for each module that has changed since the last release -- the first release will require that each module is updated with a patch release (as a result of moving into this monorepo).

---

## Note

I am beginning work as we speak on a tool to manage the changelog for each module in the `packages/` folder -- and will update our build process once I have something in the works.

**Comment by bcoe** [comment]
@stevemao I've landed the two initial features for lerna support; just waiting on publication permissions -- I believe this first publish will result in several patch releases, but as long as we've been good about keeping `master` released for each package, it should be a no-op.

**Comment by stevemao** [comment]
Sorry, you should be able to push now... Let me know if I miss any since there are too many packages...

**Comment by bcoe** [comment]
@stevemao I've been working on publishing some of the lerna updates tonight, noticed I still need access to https://www.npmjs.com/package/gulp-conventional-changelog.

**Comment by bcoe** [comment]
and `git-raw-commits`.

**Comment by bcoe** [comment]
@stevemao sorry, and also `conventional-recommended-bump`.

**Comment by stevemao** [comment]
Just learned that npm supports org now. Should be easier to add everyone!

**Comment by Tapppi** [comment]
Yeah, the orgs are really nice in my experince, we should really be using them :smile:

**Comment by stevemao** [comment]
Hi all, I created an org https://www.npmjs.com/org/conventional-changelog and added a few people. npm access should be easy to manage now. Let me know if you find any problem. Thanks!

**Comment by stevemao** [comment]
BTW, I tried the command

```
$ npm access grant read-write conventional-changelog:developers conventional-changelog
npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/whitech/.nvm/versions/node/v6.10.3/bin/node" "/Users/whitech/.nvm/versions/node/v6.10.3/bin/npm" "access" "grant" "read-write" "conventional-changelog:developers" "conventional-changelog"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code E403

npm ERR! Forbidden : -/team/conventional-changelog/developers/package
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/whitech/workdir/conventional-changelog/npm-debug.log
```

But I managed to do so successfully via the npmjs website.

**Comment by stevemao** [comment]
For some reason I can't add `grunt-conventional-changelog`. I tried removing everyone except myself but didn't work... I added @bcoe back if you could add the package to the org that'd great!

**Comment by marionebl** [comment]
@stevemao Have you reported the issue with npm support? I had similar issues when migrating commitlint to an org and they helped me out on in no time.

**Comment by marionebl** [comment]
I published new releases and noticed the [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog) main package is not writeable by the npm group: https://www.npmjs.com/org/conventional-changelog

**Comment by stevemao** [comment]
@marionebl I cannot add conventional-changelog to the org...

**Comment by stevemao** [comment]
I just sent an email to support@npmjs.com

**Comment by stevemao** [comment]
@hbetts I got an reply from npm but they didn't solve our problem yet.

**Comment by stevemao** [comment]
Looks like npm has solved our problem. Please comment if there's still problems with publishing. Thanks!

**Comment by dlmr** [comment]
Related to this; it seems like the two latest versions, currently on `1.1.9`, of [`conventional-changelog`](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog) never was published.

```
❯ npm view conventional-changelog

{ name: 'conventional-changelog',
  description: 'Generate a changelog from git metadata',
  'dist-tags': { latest: '1.1.7', next: '0.1.0-beta.3' },
  versions:
```

**Comment by hbetts** [comment]
@dlmr I [recently published `conventional-changelog`](https://github.com/conventional-changelog/conventional-changelog/pull/259#issuecomment-361121875), version `1.1.10`. Not sure what happened to versions `1.1.8` and `1.1.9`.
